// <auto-generated />
using System;
using DangersOfLazyLoadingInASPNETCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DangersOfLazyLoadingInASPNETCore.Migrations
{
    [DbContext(typeof(LazyContext))]
    [Migration("20180728040058_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DangersOfLazyLoadingInASPNETCore.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullAddress");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new { Id = 1, FullAddress = "123 Main Street" },
                        new { Id = 2, FullAddress = "124 Main Street" },
                        new { Id = 3, FullAddress = "125 Main Street" }
                    );
                });

            modelBuilder.Entity("DangersOfLazyLoadingInASPNETCore.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("People");

                    b.HasData(
                        new { Id = 1, AddressId = 1, Name = "Shawn" },
                        new { Id = 2, AddressId = 2, Name = "Tom" },
                        new { Id = 3, AddressId = 3, Name = "Sally" }
                    );
                });

            modelBuilder.Entity("DangersOfLazyLoadingInASPNETCore.Data.Person", b =>
                {
                    b.HasOne("DangersOfLazyLoadingInASPNETCore.Data.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
